apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: high-priority-pod
  name: high-priority-pod
spec:
  containers:
  - command:
    - /bin/sh
    - -c
    - while true; do echo hello; sleep 10; done
    image: ubuntu
    name: high-priority-pod
    resources: 
      requests:
        memory: "500Mi"
        cpu: "500m"
      limits:
        memory: "1Gi"
        cpu: "500m"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  priorityClassName: high
status: {}
