apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx
  name: nginx
spec:
  containers:
  - image: nginx
    name: nginx
    resources: 
      requests:
        memory: "100Mi"
        cpu: "50m"
      limits:
        memory: "1Gi"
        cpu: "100m"
  dnsPolicy: ClusterFirst
  restartPolicy: Never
  priorityClassName: low
