apiVersion: v1
kind: ResourceQuota
metadata:
  creationTimestamp: null
  name: quota-high
spec:
  hard:
    cpu: "2"
    memory: 1G
    pods: "5"
  scopeSelector:
    matchExpressions:
    - operator: In
      scopeName: PriorityClass
      values: ["high"]
